### ISSUE TITLE
[Bug]: The "Update" button appears under the window control icons

### ISSUE THREAD

**Issue by C0sm0cats** [wavetermdev/waveterm#1194] opened 2024-11-02 07:48 UTC
### Current Behavior

I am experiencing an issue with the application's interface. The "Update" button is positioned beneath the minimize, maximize, and close icons, making it difficult to click.
![image](https://github.com/user-attachments/assets/876188ac-f5d4-476a-9334-68f73197f7bd)

### Expected Behavior

The "Update" button should be clearly visible and accessible, without overlapping the window control icons.

### Steps To Reproduce

Open the application.
Observe the positioning of the "Update" button.

### Wave Version

0.9.1-beta.2

### Platform

Linux

### OS Version/Distribution

manjaro

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment] 2024-11-11 19:31
duplicate of #1173

**Closed by esimkowitz** 2024-11-11 19:31 UTC
Labels: bug, duplicate
