### ISSUE TITLE
Update to 0.7.x - Unable to SSH to Machines

### ISSUE THREAD

**Issue by oliv10** [wavetermdev/waveterm#476] opened 2024-03-19 14:40 UTC
**Describe the bug**
Unable to ssh into any machine. Reverting to an older version allows the application to SSH into other machines without issue.

**To Reproduce**
Update to version 0.7.x from 0.6.x

**Expected behavior**
ssh to work correctly.

**Screenshots**

<img width="700" alt="Screenshot 2024-03-19 at 10 12 37 AM" src="https://github.com/wavetermdev/waveterm/assets/18117030/c90d6021-90d6-490b-b6cd-0541c3d6b79f">
<img width="698" alt="Screenshot 2024-03-19 at 10 18 20 AM" src="https://github.com/wavetermdev/waveterm/assets/18117030/26fdf8e9-de9e-4ad7-8912-ca6a73768ee1">

**Desktop (please complete the following information):**
 - OS: MacOS M1 Max
 - Version 0.7.1

**Additional context**
Valid ssh sessions with no changes to my known_hosts file.

Clearing the known_hosts file did not make any changes to this issue.

<img width="753" alt="Screenshot 2024-03-19 at 10 20 00 AM" src="https://github.com/wavetermdev/waveterm/assets/18117030/f22a9f38-a888-44d7-860b-2797e983691e">

-----------------------------------

<img width="226" alt="Screenshot 2024-03-19 at 10 20 16 AM" src="https://github.com/wavetermdev/waveterm/assets/18117030/233089b3-c3e1-400d-b6ae-b720f8d72002">

**Comment by oneirocosm** [comment] 2024-03-20 02:22
Interesting--I would have expected clearing the known_hosts to at least temporarily make it go away.  I'm really hoping it isn't an underlying bug in the library we're using.  In the meantime, there are a few other things we could look at.

Which keywords are you using for this connection in your ssh_config file?  You don't need to tell me any like user and/or hostname, but it's possible there are more obscure ones that we don't support yet.

If you take a look at the known_hosts file, could you check what type of key is causing the error? (It should say before the key itself)

**Comment by stheil15** [comment] 2024-03-20 08:02
Same here after an update but different error. Ubuntu 22.04


prompt> error, invalid packet received from waveshell client: raw[which: no mshell-v0.5 in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/stheil/.mshell)]

**Comment by oliv10** [comment] 2024-03-20 16:07
<img width="678" alt="Screenshot 2024-03-20 at 12 03 18 PM" src="https://github.com/wavetermdev/waveterm/assets/18117030/33b7536b-eee2-4ef2-9dca-389a3a5dce0d">

After removing the offending lines (one of which was the machine I am attempting to connect to) from the known hosts file it then throws this error. Below are the types of keys that it was angry at.

![Screenshot 2024-03-20 at 12 03 26 PM](https://github.com/wavetermdev/waveterm/assets/18117030/bc895cdf-0a7f-40b3-ab0a-7c52d909c6bf)

**Comment by oneirocosm** [comment] 2024-03-20 21:14
@stheil15 
> Same here after an update but different error. Ubuntu 22.04
>
>prompt> error, invalid packet received from waveshell client: raw[which: no mshell-v0.5 in > (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/stheil/.mshell)]

This looks like a separate issue that I've seen in development builds but not in production. You may be able to get around it by explicitly clicking the reinstall button and waiting a few minutes. (We unfortunately don't have a good install indicator when this happens).

**Comment by oneirocosm** [comment] 2024-03-20 21:21
@oliv10
> Nothing that the 0.6.x version didn't support. I am truly unsure what caused the issue to arise all of the sudden.
We made a bunch of ssh changes in this update. Rather than using a text-based system with the regular `ssh` command, we're now using golang's `x/crypto/ssh` library. So there's a chance that these updates broke something that worked in the previous version. I imagine things like `HashKnownHosts` and `FingerprintHash` could cause some problems until more support is added.

**Comment by oneirocosm** [comment] 2024-03-20 21:26
Granted, none of that directly fixes your issue.  Did you by chance get a popup with the `remote host identification has changed` error? Typically that would mean, that waveterm is finding a different entry in `~/.ssh/known_hosts`, ~/.ssh/known_hosts2`, `/etc/ssh/known_hosts`, or `/etc/ssh/known_hosts2` for that connection, but the credentials from that file don't match what is being received. But I would expect that you'd also see this when connecting with a regular `ssh` command as well.

**Comment by oliv10** [comment] 2024-03-20 23:53
I am getting the `remote host identification has changed` error. However, when I ssh into the machine using my standard terminal it works just fine without issue. No other `known_hosts` files exist on my system either.

**Comment by oneirocosm** [comment] 2024-03-21 00:19
Would you happen to have two entries for the same remote in your known_hosts file but with different keys?

**Comment by oneirocosm** [comment] 2024-03-21 00:25
If so, it could be related to this bug https://github.com/golang/go/issues/36126

**Comment by oliv10** [comment] 2024-03-21 00:44
> Would you happen to have two entries for the same remote in your known_hosts file but with different keys?

Not after removing the three keys it was mad about.

**Comment by oneirocosm** [comment] 2024-03-21 01:10
If it is creating the three known hosts files, it likely does come from the bug I linked above. It seems like the library we're using can't handle being provided multiple key types. There is a PR to fix it, but it looks like it hasn't been touched in a while. Worst case scenario, we might be able to fork the library and implement the fix ourselves&mdash;at least until it gets merged into the original library.

**Comment by oliv10** [comment] 2024-03-21 01:47
Well, its not. Cause with the `known_hosts` file having just those three keys that it generated from ssh into it using the standard terminal. Switching back to Wave with just those created worked perfectly fine.

**Comment by oliv10** [comment] 2024-03-21 01:49
<img width="402" alt="Screenshot 2024-03-20 at 9 47 45 PM" src="https://github.com/wavetermdev/waveterm/assets/18117030/bae70d04-fb77-489a-a2c7-d8c232da6a39">

known_hosts file

<img width="695" alt="Screenshot 2024-03-20 at 9 48 40 PM" src="https://github.com/wavetermdev/waveterm/assets/18117030/63eba603-3036-457c-8b07-aa91028dd0bb">

Connection alive and happy, sans a few unrelated errors.

**Comment by oliv10** [comment] 2024-03-21 01:50
<img width="301" alt="Screenshot 2024-03-20 at 9 49 54 PM" src="https://github.com/wavetermdev/waveterm/assets/18117030/bf03c0e1-f382-4064-b237-67b0cb845e7b">

Executes commands as it would through any other terminal

**Comment by oneirocosm** [comment] 2024-03-21 19:33
Oh good&mdash;I'm glad you have a workaround!  Still, that means that we aren't writing to known_hosts properly.  If you noticed any glaring differences **(that don't require you to post your keys)** between the known_hosts we produced and the known_hosts `ssh` produced, that would be helpful!

**Comment by oliv10** [comment] 2024-03-22 00:20
> Oh good—I'm glad you have a workaround! Still, that means that we aren't writing to known_hosts properly. If you noticed any glaring differences **(that don't require you to post your keys)** between the known_hosts we produced and the known_hosts `ssh` produced, that would be helpful!

With the `known_hosts` empty and trying to connect using wave it wouldn't prompt me to create the new keys at all. So I would say that's probably the first thing to take a look at.

**Comment by psgandalf** [comment] 2024-04-18 20:50
I have the same problems. Ubuntu machines. It seams like there isn't any new line after the key is added to known_hosts. So the first one is ok. When the second is added it just appends to the first one. Manually editing the row and press enter to force a newline makes everything correct again.

**Comment by oneirocosm** [comment] 2024-04-18 21:18
I see where the issue is now. And it shouldn't be too hard to fix, so it will be in our next release.

**Comment by psgandalf** [comment] 2024-04-20 07:43
a linux build confirmes that the fix is the solution to the problem.
Thx for the quick fix.

**Comment by oneirocosm** [comment] 2024-07-05 21:12
While this fixed part of this issue, it seems the initial issue still exists as referenced here https://github.com/golang/go/issues/36126

Since that one is more active, I will close this one and continue to work on a fix there.

**Closed by oneirocosm** 2024-07-05 21:12 UTC
Labels: bug
