### ISSUE TITLE
Console file managers (mc, lf) do not seem to render and operate correctly

### ISSUE THREAD

**Issue by vtomilin** [wavetermdev/waveterm#195] opened 2023-12-25 20:07 UTC
Console file managers, the likes of Midnight Commander or lf (perhaps others, ranger?) do not render or work as expected.

**To Reproduce**
1. Run Midnight Commander or lf
2. Use arrow keys or hjkl to navigate around
3. Observe the file manager fail to render correctly

**Expected behavior**
Console file managers manage to render and be usable in Wave

**Screenshots**
<img width="1680" alt="Screenshot 2023-12-25 at 14 58 09" src="https://github.com/wavetermdev/waveterm/assets/1181134/1d493b34-ae8c-4ecb-9aab-e8bc9b8db69e">
<img width="1680" alt="Screenshot 2023-12-25 at 14 59 15" src="https://github.com/wavetermdev/waveterm/assets/1181134/026d9c85-e9ff-4c82-8186-7397424c7de1">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Version Version 14.2.1 (23C71)
 - MacBook Pro, i9, 32G RAM

**Comment by esimkowitz** [comment] 2023-12-26 17:00
Could you describe a bit more what is broken for you and could you share your configuration for midnight commander? I am not able to reproduce your issues on my end

**Comment by esimkowitz** [comment] 2023-12-26 17:04
Same for lf, I'm unable to repro

**Comment by vtomilin** [comment] 2024-02-08 02:46
@esimkowitz Apologies for a late response. Wave v0.6.1 does not appear to have this issue. Thank you!

**Comment by esimkowitz** [comment] 2024-02-08 05:44
Thank you for confirming, I'll close the issue

**Closed** 2024-02-08 05:43 UTC
Labels: bug
