### ISSUE TITLE
[Bug]: Cannot resize blocks in 0.9.2

### ISSUE THREAD

**Issue by m0rg5** [wavetermdev/waveterm#1292] opened 2024-11-15 10:02 UTC
### Current Behavior

The resize handles appear, but can't be dragged slimmer or wider. 

It also seems unintuitive that the right sidebar creates new blocks when clicking (terminal, files, web, etc), seems this action should toggle a block (in chosen position) on or off, and perhaps holding a modifier, I.e. CTL, would open an additional block if wanted. 

### Expected Behavior

resize handles work as they did in 0.7

### Steps To Reproduce

1. Macos m1, 0.9.2

### Wave Version

0.9.2

### Platform

macOS

### Architecture

arm64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [X] I don't have time to fix this right now, but maybe later

**Comment by m0rg5** [comment] 2024-11-15 10:16
I also now can't seem to roll back, have removed files (AppCleaner) and tried reinstalling, tried re-prompting the _use classic_ prompt, all to no avail on_ Macos 14.7.1 .

**Comment by esimkowitz** [comment] 2024-11-15 18:56
Can you share a recording of the resize issue? I can't reproduce this

**Comment by esimkowitz** [comment] 2024-11-15 19:05
As for the second part about having widget buttons in sidebar toggle existing blocks, that sounds like a feature suggestion rather than a bug. I would say open it as a separate feature request but honestly it's probably not something we'll pursue as it's not really compatible with our layout/block system. The idea of the blocks is that they're discrete entities that store their own state and are discarded when they close.

Additionally, the sidebar is going to be replaced pretty soon. We've got a few designs we're toying with that will make the widget picking experience more useful and will expand it to support other types of customization.  We are also working on some designs for more ephemeral blocks (the first of these designs is actually already implemented and will ship with the next release).

**Comment by m0rg5** [comment] 2024-11-16 03:34
Hey, thx for response. I actually rolled back to 0.7.6, but I'd simply be showing you a screencast of mouse pointer turning to a resize icon and me not resizing the chat column/block smaller.

This is what I've got in 0.7.6: 
![image](https://github.com/user-attachments/assets/68c2912c-fb2a-4496-a32a-fb99cc99bb45)

If it's all going to change re: sidebars, best to wait and see!

**Comment by esimkowitz** [comment] 2024-11-27 20:30
I'm going to close this issue as it seems more to do with feature deprecation between 0.7 and 0.8, rather than a bug. As mentioned above, we no longer support putting blocks in a sidebar the way we did in the old app. The current sidebar is also going away soon, once we have our updated widget picker available.

**Closed by esimkowitz** 2024-11-27 20:30 UTC
Labels: bug, need more info
